// <auto-generated />
using System;
using DinoSplicer.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DinoSplicer.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005181615_AddSpliceJobsAndOutputs")]
    partial class AddSpliceJobsAndOutputs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DinoSplicer.Api.Models.SpliceJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mode");

                    b.Property<double>("SegmentValue")
                        .HasColumnType("double precision")
                        .HasColumnName("segment_value");

                    b.Property<Guid>("SourceVideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_video_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_splice_jobs");

                    b.HasIndex("SourceVideoId")
                        .HasDatabaseName("ix_splice_jobs_source_video_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_splice_jobs_status");

                    b.ToTable("splice_jobs", (string)null);
                });

            modelBuilder.Entity("DinoSplicer.Api.Models.SpliceOutput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<int>("SegmentIndex")
                        .HasColumnType("integer")
                        .HasColumnName("segment_index");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<Guid>("SpliceJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("splice_job_id");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("storage_path");

                    b.HasKey("Id")
                        .HasName("pk_splice_outputs");

                    b.HasIndex("SpliceJobId", "SegmentIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_splice_outputs_splice_job_id_segment_index");

                    b.ToTable("splice_outputs", (string)null);
                });

            modelBuilder.Entity("DinoSplicer.Api.Models.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_videos");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_videos_status");

                    b.ToTable("videos", (string)null);
                });

            modelBuilder.Entity("DinoSplicer.Api.Models.SpliceJob", b =>
                {
                    b.HasOne("DinoSplicer.Api.Models.Video", "SourceVideo")
                        .WithMany()
                        .HasForeignKey("SourceVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_splice_jobs_videos_source_video_id");

                    b.Navigation("SourceVideo");
                });

            modelBuilder.Entity("DinoSplicer.Api.Models.SpliceOutput", b =>
                {
                    b.HasOne("DinoSplicer.Api.Models.SpliceJob", "SpliceJob")
                        .WithMany("Outputs")
                        .HasForeignKey("SpliceJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_splice_outputs_splice_jobs_splice_job_id");

                    b.Navigation("SpliceJob");
                });

            modelBuilder.Entity("DinoSplicer.Api.Models.SpliceJob", b =>
                {
                    b.Navigation("Outputs");
                });
#pragma warning restore 612, 618
        }
    }
}
